stage('Validación del commit'){
    println("hols")
    sh "/home/pipe2/hci.sh"
}

stage("Clonado del repostirio"){
    println("Otro stage")
    sh "docker ps"
}

stage("Build de la imagen"){
    println("Otro stage")
    sh "docker ps"
}

